image: maven:3.3.9-jdk-8
variables:
  SONAR_TOKEN: "7bd7071b4d49d6c473111391fdc93c81cb29c986"
  SONAR_HOST_URL: "http://10.0.14.80:9000/"
  GIT_DEPTH: 0
  NEXUS_USERNAME: "Ymx1ZXNreQ=="
  NEXUS_PASSWORD: "Ymx1ZXNreQ=="
  NEXUS_DEV_URL : "http://10.0.14.79:8081/repository/Bluesky-Dev-Releases"
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/.m2/repository"
workflow:
  rules:
    - if: $GITLAB_USER_NAME =~ /gitadmin/ && $CI_COMMIT_BRANCH =~ /feature/
      when: never
    - when: always
stages:
  - build
  - test
  - code-scan
  - package
  - publish
  - auto-merge
build:
  stage: build
  script:
    - export PROJECT=$(cat pom.xml | grep "<artifactId>"| head -1 | cut -d">" -f2 | cut -d"<" -f1)
    - export VERSION=$(cat pom.xml | grep "<version>"| head -1 | cut -d">" -f2 | cut -d"<" -f1)
    - echo Build version - ${PROJECT}-${VERSION}.war
    - mvn clean prepare-package -DskipTests=true
test:
  stage: test
  script:
    - mvn test
  allow_failure: true
code-scan:
  stage: code-scan
  script:
    - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true -DskipTests=true
  allow_failure: true
package:
  stage: package
  script:
    - export PROJECT=$(cat pom.xml | grep "<artifactId>"| head -1 | cut -d">" -f2 | cut -d"<" -f1)
    - export VERSION=$(cat pom.xml | grep "<version>"| head -1 | cut -d">" -f2 | cut -d"<" -f1)
    - echo Packaging  - ${PROJECT}-${VERSION}.war
    - mvn package -DskipTests=true
    - ls target/
  artifacts:
    paths:
    - target/*.war
  only:
    - development
    - qa
    - preprod
    - pre-production
    - prod
    - demo
    - uat
publish:
  stage: publish
  script:
    - export PROJECT=$(cat pom.xml | grep "<artifactId>"| head -1 | cut -d">" -f2 | cut -d"<" -f1)
    - export VERSION=$(cat pom.xml | grep "<version>"| head -1 | cut -d">" -f2 | cut -d"<" -f1)
    - echo Publishing  - ${PROJECT}-${VERSION}.war
    - ls target/
    - echo curl -v -u $(eval echo ${NEXUS_USERNAME} | base64 --decode):$(eval echo ${NEXUS_PASSWORD} | base64 --decode) -T target/*.war ${NEXUS_DEV_URL}/${PROJECT}/${VERSION}/${PROJECT}-${VERSION}.war
    - curl -v -u $(eval echo ${NEXUS_USERNAME} | base64 --decode):$(eval echo ${NEXUS_PASSWORD} | base64 --decode) -T target/*.war ${NEXUS_DEV_URL}/${PROJECT}/${VERSION}/${PROJECT}-${VERSION}.war
  only:
    - development
    - qa
    - preprod
    - pre-production
    - prod
    - demo
    - uat
    
auto-merge:
  stage: auto-merge
  rules:
    - if: ' $CI_COMMIT_BRANCH !~ /feature|maintenance|hotfix/ && $CI_COMMIT_BRANCH=~ /.*/ '
  tags:
    - 90-automerge-py
  script:
    - echo "auto-merge is not configured yet"
